export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

// new

export const REQUEST_CONFIRMATION = 'REQUEST_CONFIRMATION';

// new

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const RESET_CART = 'RESET_CART';
export const START_PAYMENT_PROCESS = 'START_PAYMENT_PROCESS';
export const END_PAYMENT_PROCESS = 'END_PAYMENT_PROCESS';

export const AUTH_SIGNIN_START = 'AUTH_SIGNIN_START';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAIL = 'AUTH_SIGNIN_FAIL';
export const AUTH_SIGNIN_STATUS_RESET = 'AUTH_SIGNIN_STATUS_RESET';

export const AUTH_AUTO_SIGIN = 'AUTH_AUTO_SIGIN';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_REDIRECT_PATH = 'SET_REDIRECT_PATH';